/* Generated by Yosys 0.19+42 (git sha1 7d4f87d69f0, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* hdlname = "\\counter" *)
(* src = "iiitb_rtc.v:16.1-33.10" *)
module \$paramod\counter\max_value=s32'00000000000000000000000000000010 (clk, rst, clr, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "iiitb_rtc.v:17.15-17.18" *)
  wire _17_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _18_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _19_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _20_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _21_;
  (* src = "iiitb_rtc.v:17.19-17.21" *)
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "iiitb_rtc.v:17.11-17.14" *)
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "iiitb_rtc.v:17.7-17.10" *)
  input clk;
  wire clk;
  (* src = "iiitb_rtc.v:17.15-17.18" *)
  input clr;
  wire clr;
  (* init = 4'h0 *)
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "iiitb_rtc.v:17.19-17.21" *)
  input en;
  wire en;
  (* src = "iiitb_rtc.v:17.11-17.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__or3b_1 _41_ (
    .A(_21_),
    .B(_20_),
    .C_N(_19_),
    .X(_23_)
  );
  sky130_fd_sc_hd__a21oi_1 _42_ (
    .A1(_22_),
    .A2(_23_),
    .B1(_18_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand2b_1 _43_ (
    .A_N(_17_),
    .B(_32_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a211oi_1 _44_ (
    .A1(_22_),
    .A2(_18_),
    .B1(_24_),
    .C1(_25_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__or3b_1 _45_ (
    .A(_21_),
    .B(_20_),
    .C_N(_22_),
    .X(_26_)
  );
  sky130_fd_sc_hd__a22oi_1 _46_ (
    .A1(_22_),
    .A2(_18_),
    .B1(_26_),
    .B2(_19_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__and3_1 _47_ (
    .A(_22_),
    .B(_19_),
    .C(_18_),
    .X(_28_)
  );
  sky130_fd_sc_hd__nor3_1 _48_ (
    .A(_25_),
    .B(_27_),
    .C(_28_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand4_1 _49_ (
    .A(_22_),
    .B(_20_),
    .C(_19_),
    .D(_18_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(_20_),
    .B(_28_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nor3b_1 _51_ (
    .A(_30_),
    .B(_25_),
    .C_N(_29_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xor2_1 _52_ (
    .A(_21_),
    .B(_29_),
    .X(_31_)
  );
  sky130_fd_sc_hd__nor2_1 _53_ (
    .A(_25_),
    .B(_31_),
    .Y(_16_)
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_34_),
    .Q(count[0])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_36_),
    .Q(count[1])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_38_),
    .Q(count[2])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_40_),
    .Q(count[3])
  );
  assign _21_ = count[3];
  assign _22_ = en;
  assign _20_ = count[2];
  assign _19_ = count[1];
  assign _18_ = count[0];
  assign _17_ = clr;
  assign _32_ = rst;
  assign _34_ = _13_;
  assign _36_ = _14_;
  assign _38_ = _15_;
  assign _40_ = _16_;
endmodule

(* hdlname = "\\counter" *)
(* src = "iiitb_rtc.v:16.1-33.10" *)
module \$paramod\counter\max_value=s32'00000000000000000000000000000101 (clk, rst, clr, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "iiitb_rtc.v:17.15-17.18" *)
  wire _17_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _18_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _19_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _20_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _21_;
  (* src = "iiitb_rtc.v:17.19-17.21" *)
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "iiitb_rtc.v:17.11-17.14" *)
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "iiitb_rtc.v:17.7-17.10" *)
  input clk;
  wire clk;
  (* src = "iiitb_rtc.v:17.15-17.18" *)
  input clr;
  wire clr;
  (* init = 4'h0 *)
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "iiitb_rtc.v:17.19-17.21" *)
  input en;
  wire en;
  (* src = "iiitb_rtc.v:17.11-17.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__nand2b_1 _41_ (
    .A_N(_17_),
    .B(_32_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_22_),
    .B(_18_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _43_ (
    .A(_23_),
    .B(_24_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2b_1 _44_ (
    .A_N(_21_),
    .B(_20_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a31oi_1 _45_ (
    .A1(_22_),
    .A2(_18_),
    .A3(_25_),
    .B1(_19_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__and3_1 _46_ (
    .A(_22_),
    .B(_19_),
    .C(_18_),
    .X(_27_)
  );
  sky130_fd_sc_hd__nor3_1 _47_ (
    .A(_23_),
    .B(_26_),
    .C(_27_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2b_1 _48_ (
    .A_N(_19_),
    .B(_21_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a41oi_1 _49_ (
    .A1(_22_),
    .A2(_20_),
    .A3(_18_),
    .A4(_28_),
    .B1(_23_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__o21a_1 _50_ (
    .A1(_20_),
    .A2(_27_),
    .B1(_29_),
    .X(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _51_ (
    .A1(_20_),
    .A2(_27_),
    .B1(_21_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__and3_1 _52_ (
    .A(_21_),
    .B(_20_),
    .C(_27_),
    .X(_31_)
  );
  sky130_fd_sc_hd__nor3_1 _53_ (
    .A(_23_),
    .B(_30_),
    .C(_31_),
    .Y(_16_)
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_34_),
    .Q(count[0])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_36_),
    .Q(count[1])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_38_),
    .Q(count[2])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_40_),
    .Q(count[3])
  );
  assign _21_ = count[3];
  assign _22_ = en;
  assign _20_ = count[2];
  assign _19_ = count[1];
  assign _18_ = count[0];
  assign _17_ = clr;
  assign _32_ = rst;
  assign _34_ = _13_;
  assign _36_ = _14_;
  assign _38_ = _15_;
  assign _40_ = _16_;
endmodule

(* hdlname = "\\counter" *)
(* src = "iiitb_rtc.v:16.1-33.10" *)
module \$paramod\counter\max_value=s32'00000000000000000000000000001001 (clk, rst, clr, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "iiitb_rtc.v:17.15-17.18" *)
  wire _17_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _18_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _19_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _20_;
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  wire _21_;
  (* src = "iiitb_rtc.v:17.19-17.21" *)
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "iiitb_rtc.v:17.11-17.14" *)
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "iiitb_rtc.v:17.7-17.10" *)
  input clk;
  wire clk;
  (* src = "iiitb_rtc.v:17.15-17.18" *)
  input clr;
  wire clr;
  (* init = 4'h0 *)
  (* src = "iiitb_rtc.v:18.18-18.23" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "iiitb_rtc.v:17.19-17.21" *)
  input en;
  wire en;
  (* src = "iiitb_rtc.v:17.11-17.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2b_1 _41_ (
    .A(_17_),
    .B_N(_32_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nand2_1 _42_ (
    .A(_22_),
    .B(_18_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__o21ai_0 _43_ (
    .A1(_22_),
    .A2(_18_),
    .B1(_23_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21oi_1 _44_ (
    .A1(_22_),
    .A2(_18_),
    .B1(_25_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2b_1 _45_ (
    .A_N(_20_),
    .B(_21_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a31oi_1 _46_ (
    .A1(_22_),
    .A2(_18_),
    .A3(_26_),
    .B1(_19_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__and3_1 _47_ (
    .A(_22_),
    .B(_19_),
    .C(_18_),
    .X(_28_)
  );
  sky130_fd_sc_hd__nor3b_1 _48_ (
    .A(_27_),
    .B(_28_),
    .C_N(_23_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _49_ (
    .A1(_20_),
    .A2(_28_),
    .B1(_23_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a21oi_1 _50_ (
    .A1(_20_),
    .A2(_28_),
    .B1(_29_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o31ai_1 _51_ (
    .A1(_19_),
    .A2(_24_),
    .A3(_26_),
    .B1(_23_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a21oi_1 _52_ (
    .A1(_20_),
    .A2(_28_),
    .B1(_21_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a311oi_1 _53_ (
    .A1(_21_),
    .A2(_20_),
    .A3(_28_),
    .B1(_30_),
    .C1(_31_),
    .Y(_16_)
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_34_),
    .Q(count[0])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_36_),
    .Q(count[1])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_38_),
    .Q(count[2])
  );
  (* src = "iiitb_rtc.v:21.1-32.4" *)
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_40_),
    .Q(count[3])
  );
  assign _21_ = count[3];
  assign _22_ = en;
  assign _20_ = count[2];
  assign _19_ = count[1];
  assign _18_ = count[0];
  assign _17_ = clr;
  assign _32_ = rst;
  assign _34_ = _13_;
  assign _36_ = _14_;
  assign _38_ = _15_;
  assign _40_ = _16_;
endmodule

(* top =  1  *)
(* src = "iiitb_rtc.v:1.1-14.10" *)
module iiitb_rtc(clkin, rst, hrm, hrl, minm, minl, secm, secl);
  (* src = "iiitb_rtc.v:10.57-10.67" *)
  wire _00_;
  (* src = "iiitb_rtc.v:10.56-10.84" *)
  wire _01_;
  (* src = "iiitb_rtc.v:11.56-11.100" *)
  wire _02_;
  (* src = "iiitb_rtc.v:12.57-12.117" *)
  wire _03_;
  (* src = "iiitb_rtc.v:13.57-13.132" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "iiitb_rtc.v:10.57-10.67" *)
  wire _26_;
  (* src = "iiitb_rtc.v:10.56-10.84" *)
  wire _27_;
  (* src = "iiitb_rtc.v:11.56-11.100" *)
  wire _28_;
  (* src = "iiitb_rtc.v:12.57-12.117" *)
  wire _29_;
  (* src = "iiitb_rtc.v:13.57-13.132" *)
  wire _30_;
  (* src = "iiitb_rtc.v:5.6-5.11" *)
  wire _31_;
  (* src = "iiitb_rtc.v:3.17-3.20" *)
  wire _32_;
  (* src = "iiitb_rtc.v:3.17-3.20" *)
  wire _33_;
  (* src = "iiitb_rtc.v:3.17-3.20" *)
  wire _34_;
  (* src = "iiitb_rtc.v:3.17-3.20" *)
  wire _35_;
  (* src = "iiitb_rtc.v:3.13-3.16" *)
  wire _36_;
  (* src = "iiitb_rtc.v:3.13-3.16" *)
  wire _37_;
  (* src = "iiitb_rtc.v:3.13-3.16" *)
  wire _38_;
  (* src = "iiitb_rtc.v:3.13-3.16" *)
  wire _39_;
  (* src = "iiitb_rtc.v:3.26-3.30" *)
  wire _40_;
  (* src = "iiitb_rtc.v:3.26-3.30" *)
  wire _41_;
  (* src = "iiitb_rtc.v:3.26-3.30" *)
  wire _42_;
  (* src = "iiitb_rtc.v:3.26-3.30" *)
  wire _43_;
  (* src = "iiitb_rtc.v:3.21-3.25" *)
  wire _44_;
  (* src = "iiitb_rtc.v:3.21-3.25" *)
  wire _45_;
  (* src = "iiitb_rtc.v:3.21-3.25" *)
  wire _46_;
  (* src = "iiitb_rtc.v:3.21-3.25" *)
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  (* src = "iiitb_rtc.v:3.36-3.40" *)
  wire _58_;
  (* src = "iiitb_rtc.v:3.36-3.40" *)
  wire _59_;
  (* src = "iiitb_rtc.v:3.36-3.40" *)
  wire _60_;
  (* src = "iiitb_rtc.v:3.36-3.40" *)
  wire _61_;
  (* src = "iiitb_rtc.v:3.31-3.35" *)
  wire _62_;
  (* src = "iiitb_rtc.v:3.31-3.35" *)
  wire _63_;
  (* src = "iiitb_rtc.v:3.31-3.35" *)
  wire _64_;
  (* src = "iiitb_rtc.v:3.31-3.35" *)
  wire _65_;
  (* src = "iiitb_rtc.v:2.7-2.12" *)
  input clkin;
  wire clkin;
  (* src = "iiitb_rtc.v:5.6-5.11" *)
  wire hrclr;
  (* src = "iiitb_rtc.v:3.17-3.20" *)
  output [3:0] hrl;
  wire [3:0] hrl;
  (* src = "iiitb_rtc.v:3.13-3.16" *)
  output [3:0] hrm;
  wire [3:0] hrm;
  (* src = "iiitb_rtc.v:3.26-3.30" *)
  output [3:0] minl;
  wire [3:0] minl;
  (* src = "iiitb_rtc.v:3.21-3.25" *)
  output [3:0] minm;
  wire [3:0] minm;
  (* src = "iiitb_rtc.v:2.13-2.16" *)
  input rst;
  wire rst;
  (* src = "iiitb_rtc.v:3.36-3.40" *)
  output [3:0] secl;
  wire [3:0] secl;
  (* src = "iiitb_rtc.v:3.31-3.35" *)
  output [3:0] secm;
  wire [3:0] secm;
  sky130_fd_sc_hd__nor4bb_1 _66_ (
    .A(_59_),
    .B(_60_),
    .C_N(_61_),
    .D_N(_58_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nor2_1 _67_ (
    .A(_63_),
    .B(_65_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__and2_0 _68_ (
    .A(_62_),
    .B(_64_),
    .X(_49_)
  );
  sky130_fd_sc_hd__and3_1 _69_ (
    .A(_26_),
    .B(_48_),
    .C(_49_),
    .X(_27_)
  );
  sky130_fd_sc_hd__nor4bb_1 _70_ (
    .A(_41_),
    .B(_42_),
    .C_N(_43_),
    .D_N(_40_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__nand4_1 _71_ (
    .A(_26_),
    .B(_48_),
    .C(_49_),
    .D(_50_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__clkinv_1 _72_ (
    .A(_51_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nor2_1 _73_ (
    .A(_45_),
    .B(_47_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__nand3_1 _74_ (
    .A(_44_),
    .B(_46_),
    .C(_52_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nor2_1 _75_ (
    .A(_51_),
    .B(_53_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor4b_1 _76_ (
    .A(_36_),
    .B(_39_),
    .C(_38_),
    .D_N(_37_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__nor2b_1 _77_ (
    .A(_34_),
    .B_N(_32_),
    .Y(_55_)
  );
  sky130_fd_sc_hd__nand4b_1 _78_ (
    .A_N(_35_),
    .B(_54_),
    .C(_55_),
    .D(_33_),
    .Y(_56_)
  );
  sky130_fd_sc_hd__nor3_1 _79_ (
    .A(_51_),
    .B(_53_),
    .C(_56_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nand3b_1 _80_ (
    .A_N(_33_),
    .B(_35_),
    .C(_55_),
    .Y(_57_)
  );
  sky130_fd_sc_hd__nor3_1 _81_ (
    .A(_51_),
    .B(_53_),
    .C(_57_),
    .Y(_30_)
  );
  (* src = "iiitb_rtc.v:8.16-8.75" *)
  \$paramod\counter\max_value=s32'00000000000000000000000000001001  c1 (
    .clk(clkin),
    .clr(1'h0),
    .count(secl),
    .en(1'h1),
    .rst(rst)
  );
  (* src = "iiitb_rtc.v:9.16-9.81" *)
  \$paramod\counter\max_value=s32'00000000000000000000000000000101  c2 (
    .clk(clkin),
    .clr(1'h0),
    .count(secm),
    .en(_00_),
    .rst(rst)
  );
  (* src = "iiitb_rtc.v:10.16-10.99" *)
  \$paramod\counter\max_value=s32'00000000000000000000000000001001  c3 (
    .clk(clkin),
    .clr(1'h0),
    .count(minl),
    .en(_01_),
    .rst(rst)
  );
  (* src = "iiitb_rtc.v:11.16-11.115" *)
  \$paramod\counter\max_value=s32'00000000000000000000000000000101  c4 (
    .clk(clkin),
    .clr(1'h0),
    .count(minm),
    .en(_02_),
    .rst(rst)
  );
  (* src = "iiitb_rtc.v:12.16-12.131" *)
  \$paramod\counter\max_value=s32'00000000000000000000000000001001  c5 (
    .clk(clkin),
    .clr(hrclr),
    .count(hrl),
    .en(_03_),
    .rst(rst)
  );
  (* src = "iiitb_rtc.v:13.16-13.146" *)
  \$paramod\counter\max_value=s32'00000000000000000000000000000010  c6 (
    .clk(clkin),
    .clr(hrclr),
    .count(hrm),
    .en(_04_),
    .rst(rst)
  );
  assign _58_ = secl[0];
  assign _59_ = secl[1];
  assign _60_ = secl[2];
  assign _61_ = secl[3];
  assign _00_ = _26_;
  assign _63_ = secm[1];
  assign _62_ = secm[0];
  assign _65_ = secm[3];
  assign _64_ = secm[2];
  assign _01_ = _27_;
  assign _41_ = minl[1];
  assign _40_ = minl[0];
  assign _42_ = minl[2];
  assign _43_ = minl[3];
  assign _02_ = _28_;
  assign _45_ = minm[1];
  assign _44_ = minm[0];
  assign _47_ = minm[3];
  assign _46_ = minm[2];
  assign _03_ = _29_;
  assign _32_ = hrl[0];
  assign _33_ = hrl[1];
  assign _34_ = hrl[2];
  assign _35_ = hrl[3];
  assign _36_ = hrm[0];
  assign _37_ = hrm[1];
  assign _39_ = hrm[3];
  assign _38_ = hrm[2];
  assign hrclr = _31_;
  assign _04_ = _30_;
endmodule
